version: '3.7'

services:
  app:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
    - .:/var/www/app
    environment:
      APP_ENV: 'dev'
      APP_DEBUG: 1
      APP_MY_VAR: ${USER}

  web:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    volumes:
      - .:/var/www/app
    ports:
    - 8008:80
